apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::498205365270:role/eksctl-spot-cluster-nodegroup-spo-NodeInstanceRole-1MPT3CPR3FIHZ
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::498205365270:user/roboshop-admin
      username: roboshop-admin
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-03T10:53:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1310"
  uid: f36252b3-d38c-4bc2-89bd-998bdb4e2279


