apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::505159336758:role/eksctl-spot-cluster-nodegroup-spo-NodeInstanceRole-1N3SFW17FW08Q
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::505159336758:user/roboshop-admin
      username: roboshop-admin

kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-02T08:28:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1256"
  uid: e49efb35-8136-46bc-ace5-bc54becff7af


