apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::505159336758:role/eksctl-spot-cluster-nodegroup-spo-NodeInstanceRole-1N3SFW17FW08Q
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::505159336758:user/roboshop-admin
      username: roboshop-admin
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::505159336758:role/eksctl-spot-cluster-nodegroup-spo-NodeInstanceRole-1N3SFW17FW08Q\n  username: system:node:{{EC2PrivateDNSName}}\n","mapUsers":"- userarn: arn:aws:iam::505159336758:user/roboshop-admin\n  username: roboshop-admin\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2023-08-02T08:28:02Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"1256","uid":"e49efb35-8136-46bc-ace5-bc54becff7af"}}
  creationTimestamp: "2023-08-02T08:28:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "12067"
  uid: e49efb35-8136-46bc-ace5-bc54becff7af
