apiVersion: v1
data:
  mapRoles: |
    - userarn: arn:aws:iam::505159336758:user/roboshop-admin
      username: roboshop-admin
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- userarn: arn:aws:iam::505159336758:user/roboshop-admin\n  username: roboshop-admin\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2023-08-01T10:07:01Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"1195","uid":"0708addb-0f21-4ef7-aca2-4134986f4e60"}}
  creationTimestamp: "2023-08-01T10:25:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4370"
  uid: 1c2d8d83-eb4f-4164-b096-9909a91c0fdb
