apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::505159336758:role/eksctl-spot-cluster-nodegroup-ng-NodeInstanceRole-1EBTS3VTRWQ4V
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: rn:aws:iam::505159336758:user/roboshop-admin
      username: roboshop-admin  
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-01T12:01:39Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1140"
  uid: b2162e08-ae04-4044-b32a-3c71871ff9b7
